# $HOME/.config/alacritty/alacritty.toml
[general]
import = [
    # "~/.config/alacritty/themes/catppuccin.toml"
    "~/.config/alacritty/themes/kanso_ink.toml"
]

[window]
opacity = 0.95
blur = true 
padding.x = 8 
padding.y = 8 

decorations = "Full"
decorations_theme_variant = "Dark" 

[font]
normal.family = "BlexMono Nerd Font Mono"
bold.family = "BlexMono Nerd Font Mono"
italic.family = "BlexMono Nerd Font Mono"
bold_italic.family = "BlexMono Nerd Font Mono"
# normal.family = "IBM Plex Mono"
# bold.family = "IBM Plex Mono"
# italic.family = "IBM Plex Mono"
# bold_italic.family = "IBM Plex Mono"


offset.x = 1
offset.y = 1

size = 15.0
