#!/usr/bin/env sh

# Get week number
week() {
	date +%V
}

month() {
	date +%m
}

dka() {
	docker container kill $(dk ps -q)
}

q() {
	exit
}

dl() {
	cd $HOME/Downloads && ls
}

tree() {
	lsd --tree
}

left() {
	ls -t -1
}

# The last command with sudo
please() {
	sudo $(fc -ln -1)
}

upload() {
	curl -F"file=@$(pwd)/$1" https://0x0.st
}

unzip() {
	bsdtar xvf $1
}

search() {
  query="$*"
  open "https://www.google.com/search?q=$query"
}

ven() {
	cd $HOME/workspace/ventura && lsd
}

function mktouch () {
  for p in $@; do
    mkdir -p $(dirname "$p")
  done

  touch $@
}

function png2webp () {
  for file in *; do
      cwebp -q 100 "$file" -o "${file%.png}.webp"
  done
}

function clean-branches(){
  git branch | grep -v 'main' | xargs git branch -D
}
