
[colors]
primary.background = "#14171d"
primary.foreground = "#c5c9c7"

[colors.normal]
black   = "#14171d"
red     = "#c4746e"
green   = "#8a9a7b"
yellow  = "#c4b28a"
blue    = "#8ba4b0"
magenta = "#a292a3"
cyan    = "#8ea4a2"
white   = "#c8c093"

[colors.bright]
black   = "#a4a7a4"
red     = "#e46876"
green   = "#87a987"
yellow  = "#e6c384"
blue    = "#7fb4ca"
magenta = "#938aa9"
cyan    = "#7aa89f"
white   = "#c5c9c7"

[colors.cursor]
text   = "#14171d"
cursor = "#c5c9c7"

[colors.selection]
text       = "#c5c9c7"
background = "#393B42"
